name: task_manager
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  
  # Data Storage
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3+1
  path: ^1.9.0
  
  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.2
  
  # JSON Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  
  # Date/Time
  intl: ^0.20.2
  
  # Localization
  flutter_localizations:
    sdk: flutter
  
  # Local Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  
  # Permission Handling
  permission_handler: ^11.3.1
  
  # UI Components  
  cupertino_icons: ^1.0.8
  
  # Utils
  uuid: ^4.4.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  injectable_generator: ^2.6.1

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

